.\" 20100210
.TH "TrueCrypt" "1" "February 10, 2010"
.SH "NAME"
TrueCrypt \- Free open-source disk encryption software
.SH "DESCRIPTION"
.B TrueCrypt
is a software system for establishing and maintaining an on-the-fly-encrypted volume (data storage device). On-the-fly encryption means that data are automatically encrypted or decrypted right before they are loaded or saved, without any user intervention. No data stored on an encrypted volume can be read (decrypted) without using the correct password/keyfile(s) or correct encryption keys. Entire file system is encrypted (e.g., file names, folder names, contents of every file, free space, meta data, etc).
.PP
.SH "AUTHORS"
This manual page was written by Alexander Pozdnyakov <almipo@mail.ru>,
